import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import "./globals.css";
import type { Metadata } from "next";

import { getServerSession } from "next-auth";
import SessionProvider from "@/utils/SessionProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  session, // Terima session sebagai prop
}: {
  children: React.ReactNode;
  session: any; // Gantilah any dengan tipe sesuai dengan session Anda
}) {

  return (
    <html lang="en">
      <body>
        <SessionProvider session={session}>
          <div>
            {children}
          </div>
        </SessionProvider>
        <Footer/>
      </body>
    </html>
  );
}